name: Publish Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: true

env:
  DOCS_DIRECTORY: .
  DOCS_REQUIREMENTS_FILE: requirements.txt
  DOCS_SOURCE_DIRECTORY: source
  DOCS_BUILD_DIRECTORY: build
  DOCS_SITE_DIRECTORY: build/html

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Build documentation site
        uses: CAVISE/pipelines/actions/documentation-build@main
        with:
          docs-directory: ${{ env.DOCS_DIRECTORY }}
          requirements-file: ${{ env.DOCS_REQUIREMENTS_FILE }}
          source-directory: ${{ env.DOCS_SOURCE_DIRECTORY }}
          build-directory: ${{ env.DOCS_BUILD_DIRECTORY }}
          site-directory: ${{ env.DOCS_SITE_DIRECTORY }}

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ${{ env.DOCS_DIRECTORY }}/${{ env.DOCS_SITE_DIRECTORY }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        name: Deploy GitHub Pages
        uses: actions/deploy-pages@v5
